-- Tabla de clientes mejorada
CREATE TABLE public.clientes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying NOT NULL,
  apellido_paterno character varying NOT NULL,
  apellido_materno character varying NOT NULL,
  email character varying,
  telefono character varying,
  direccion character varying,
  comentarios text,
  fecha_registro timestamp with time zone DEFAULT now()
);

-- Tabla de eventos mejorada
CREATE TABLE public.eventos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_evento character varying NOT NULL,
  ubicacion_evento character varying,
  fecha_evento date NOT NULL,
  capacidad integer,
  precio_estandar numeric DEFAULT 0.00,
  total_bruto_cobrado numeric DEFAULT 0.00,
  total_gastado numeric DEFAULT 0.00,
  estado character varying DEFAULT 'programado',
  comentarios text,
  fecha_registro timestamp with time zone DEFAULT now(),
  CONSTRAINT estado_valido CHECK (estado IN ('programado', 'completado', 'cancelado'))
);

-- Tabla de asistencias mejorada
CREATE TABLE public.asistencias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente integer NOT NULL,
  id_evento integer NOT NULL,
  asistio boolean DEFAULT false,
  estado_pago character varying DEFAULT 'pendiente',
  monto_pagado numeric DEFAULT 0.00,
  comentarios text,
  fecha_registro timestamp with time zone DEFAULT now(),
  CONSTRAINT fk_evento FOREIGN KEY (id_evento) REFERENCES public.eventos(id),
  CONSTRAINT fk_cliente FOREIGN KEY (id_cliente) REFERENCES public.clientes(id),
  CONSTRAINT estado_pago_valido CHECK (estado_pago IN ('pendiente', 'pagado', 'parcial', 'gratuito'))
);

-- Tabla de referidos mejorada
CREATE TABLE public.referidos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_referidor integer NOT NULL,
  id_referido integer,
  nombre_referido character varying,
  email_referido character varying,
  telefono_referido character varying,
  estado character varying DEFAULT 'pendiente',
  comentarios text,
  fecha_referencia timestamp with time zone DEFAULT now(),
  CONSTRAINT fk_referidor FOREIGN KEY (id_referidor) REFERENCES public.clientes(id),
  CONSTRAINT fk_referido FOREIGN KEY (id_referido) REFERENCES public.clientes(id),
  CONSTRAINT estado_valido CHECK (estado IN ('pendiente', 'contactado', 'convertido', 'rechazado')),
  CONSTRAINT referido_info CHECK ((id_referido IS NOT NULL) OR (nombre_referido IS NOT NULL AND (email_referido IS NOT NULL OR telefono_referido IS NOT NULL)))
); 