name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create .env file
      run: |
        echo "${{ secrets.VITE_ENV_VARS }}" > .env
        echo "Created .env file"
        echo "Checking if .env file exists:"
        ls -la .env
        echo "Environment variables available:"
        env | grep VITE_ || echo "No VITE_ variables found in environment"
    
    - name: Build
      run: |
        echo "Building application..."
        echo "Checking .env file before build:"
        ls -la .env || echo ".env file not found"
        npm run build
        echo "Build completed. Checking dist directory:"
        ls -la dist/
        echo "Checking if index.html exists:"
        ls -la dist/index.html || echo "index.html not found in dist"
      env:
        NODE_ENV: production
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 